language: ruby
rvm:
- 2.2.0
sudo: false
before_script:
    - git config --global user.email "bouanto@zoho.com"
    - git config --global user.name "Antoni Boucher"
script: bundle exec rake deploy
env:
  global:
    secure: TCGdxTrN5trii/7gNsW80LAKCWCotteKXsRoYjb71Elv3bXWcBMkVITimWKh3sZecM+DYW9N2ogB5nM92/lIFihWCSSClDQIyFpm3cT+lQxbXfGkvVlRmlSDLFnrWnUCnldodD2xH/7v0O/FgMy//X2V7dp1Czp7kBGLa1laUyIDoWo1kDuvFzRMQQrbsLKoMWGx1ea9Z9PjlzI7lUsLxVq0nqiJIEWr+78R4OdVnwizbzy5hVJ5z4z1hOmYgLiQsuAbw9P44IzX2X4h5czaImjJ8lLvgM4ykAO8u5WOYCGLQ4/vTamM6V2ZzAfnnLo2S+Y3He193OXNKo7OTpIRLi0ELB7BAY67oNG0s3bu7I3ALxcE2sf8heyQK5PboKJQbo9x5pe8/DWCJ4v0+ObRsTzEBmDLpQOBrw4sEH1Z3euALM+iW+WfyvAHDjXoyhRKYza12LnTNfr/HZmdlqJWy36KpH2trt1Oa297B0OF7IM3o44H3X8YsinqQiTWuGkK3Ux7VptCE55U4hUBAjANl5W6cOtrk+ZSPd1sYD6ojNklSR1wqtD7+f4ldHzXdIWP0oaKjnQ2o4bp0gwi7oeQrBQxSu54O2dTdTgD0yAtlTLpTEB7DCX3vVOK8zlliaWNQ6yo3Bof0sAmjQIN17yri6KKV5Xz2PDnje51bMhXqJI=
