language: ruby
rvm:
- 2.2.7
sudo: false
before_script:
- git config --global user.email "bouanto@zoho.com"
- git config --global user.name "Antoni Boucher"
script: bundle exec rake deploy
env:
  global:
    secure: akFkORIkF0OGTMvDi5cCbf5pJGSA6EHIsC9SqM3HsXHDsoYGYO2ECkcy237kHh9+WbdDIetkixBDxvco6NZ1ID4aX5PSZOS9/RkeJwo8JxuNFTVMxoBGdFZWD91y1HN9WVfGfOyStaDTQwiKiwyH0oTf4sYeNAOc1lfL4e/f+t+hTraa4hMY+9enrhJqoXLfvVUMAKSGW6LEdZbdPb65ZYm6aRk4aFd4UHwmtWElXcUjBahnCcSiXxCagZog3hboYJAAq8UxCsH2d9sdCdpGaei3DZY3TYBB/WwJPUEniFUuPykz2qs2AM5cQm6a3np6iVuo+cfwQIx+YezYyPaHtxig9zBPi9uJOEbC/2YQ3BoxbTuQoneqUYV8ScnLt0eepRjXUfn4i8cJXhMSEimMZk+33m6bXB8y9+5bcPS1pWf+/HZydPkmlttqErQCWqpqJ0stBOpfU+04Dytdjbvik6ZE4hCPqtd7j6IPGCL6I/YlCI0WKghr3yCKRehwkVglcExdhemJu2nvKv9mHjL5mNGr1wucyarVIcqLU6MtlJ6fNTP1Ww6f5U/UBRfrFwnZed8Nqni1bBtsAVsvyCHpnjXLPBHteg+gc4nKlwlDErtW9hmdyyTFGVl4e3IGpycUwUuOgqn0bj06pd+chIg7Kr+d/DbCpcDbE07xnordbAg=
